import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageBanner from "@/components/PageBanner";
import { Gavel, FileText, Users, Shield, Ban, Scale, Info, MessageSquare, Lock, UserCheck, Phone, Mail, BookOpen, AlertTriangle, Landmark, CreditCard, Repeat, Globe, ShieldCheck, BadgePercent, Handshake } from "lucide-react";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <PageBanner
        title="Terms & Conditions"
        subtitle="Please read our terms carefully before using our matrimonial seva."
        backgroundImage="https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1920&h=600&fit=crop"
      />

      <div className="container mx-auto px-4 py-16 max-w-5xl">
        <div className="grid gap-12">
          {/* Preamble */}
          <section>
            <p className="text-muted-foreground text-justify leading-relaxed">
              Welcome to the Brahmin Organisation of India's matrimonial platform (herein referred to as "the Platform"). This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed mt-4">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021 that require publishing the rules and regulations, privacy policy and the terms and conditions for access or usage of our platform.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed mt-4 font-semibold">
              PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE PLATFORM. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS ("Agreement"). If you do not want to be bound by the Terms and Conditions, you must not use the Platform or its Services.
            </p>
          </section>
          
          {/* Scope */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Info className="w-6 h-6 text-primary" />
              Scope
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              You understand and acknowledge that the Platform acts as an "Intermediary" as defined under clause (1) sub-clause (w) of Section 2 of the Information Technology Act, 2000. The Platform is a brand owned by the Brahmin Organisation of India ("the Organisation") which owns, retains and has complete rights in the Platform and its services.
            </p>
             <p className="text-muted-foreground text-justify leading-relaxed mt-4">
              The Platform acts as a platform to enable any user to themselves register on it to voluntarily search for profile(s) from the database of already registered users, for seeking prospective lawful matrimonial alliances for themselves. Our volunteers may also be able to assist you to create your profile; however, you must have a valid/operational mobile phone number and an email id. The profiles in the database are classified broadly on the basis of community and region for the ease and convenience of its members. Members are provided with free/paid access for searching profiles from the database, as per the partner preference set by you, and you can shortlist the profiles in which you are interested.
            </p>
          </section>

          {/* 1. Eligibility */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <UserCheck className="w-6 h-6 text-primary" />
              1. Eligibility
            </h2>
            <p className="text-muted-foreground mb-2 font-semibold">A) Membership and rights of admission is reserved solely for:</p>
            <ul className="list-roman list-inside space-y-2 text-muted-foreground ml-4">
              <li>Indian Nationals & Citizens.</li>
              <li>Persons of Indian Origin (PIO).</li>
              <li>Non Resident Indians (NRI).</li>
              <li>Persons of Indian Descent or Indian Heritage.</li>
              <li>Persons who intend to marry persons of Indian Origin.</li>
            </ul>
            <p className="text-muted-foreground mt-4 mb-2 font-semibold">B) Further, in capacity as a member you confirm that you are:</p>
            <ul className="list-roman list-inside space-y-2 text-muted-foreground ml-4">
              <li>18 years or above (if you are a woman) or 21 years or above (if you are a man).</li>
              <li>If you have applied for Divorce, you may register by stating "Awaiting Divorce".</li>
              <li>If you are a resident of any other Country, you are legally competent to marry as per the local rules applicable to your country and you shall comply with the Indian laws for marrying a person of Indian Origin.</li>
            </ul>
            <p className="text-muted-foreground mt-4 mb-2 font-semibold">C) In case you are a Registrant of the prospective bride/ bridegroom:</p>
             <p className="text-muted-foreground text-justify leading-relaxed ml-4">
              If you have created a profile on behalf of them or are accessing the Platform on behalf of them, this implies that you have taken their consent for their profile creation and for accessing the Platform.
            </p>
          </section>

          {/* 2. Registration */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <FileText className="w-6 h-6 text-primary" />
              2. Registration
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed mb-4">
              <strong>A.</strong> We expect that you would complete the online registration process with fairness and honesty in furnishing true, accurate, current, complete information and with providing recent photos of you. We expect you to read the relevant column before keying in the details. You are requested not to key in details of the profile in fields other than the applicable field.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed mb-4">
              <strong>B.</strong> If at any point of time we come to know or have reasons to believe that any information provided by you for registration (including photos) is found to be untrue, inaccurate, or incomplete, we shall have the full right to suspend or terminate your membership and forfeit any amount paid by you.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed mb-4">
              <strong>C.</strong> We also reserve the right to block the registration of your profile if contact details/links are entered in irrelevant fields or if there are errors in any data entered.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed mb-4">
              <strong>D.</strong> Registration of duplicate profiles of the same person is not allowed. We shall have full right to suspend or terminate such duplicate profiles.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed">
              <strong>E.</strong> You acknowledge and confirm that your registration is with the bonafide intention of marriage and not otherwise. Membership is restricted strictly to the registered individual member only. Organizations, companies, businesses and/or individuals carrying on similar or competitive business cannot become Members.
            </p>
          </section>

          {/* 3. Account Security */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Lock className="w-6 h-6 text-primary" />
              3. Account Security
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              You are responsible for safeguarding the confidentiality of your login credentials such as your user id, password, OTP, etc., and for restricting access to your computer/mobile to prevent unauthorized access to your account. We do not ask for your Password and you are cautioned not to share your password with any persons. You agree to accept responsibility for all activities that occur under your account.
            </p>
          </section>

          {/* 4. Role and Responsibility of the Platform */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Shield className="w-6 h-6 text-primary" />
              4. Role and Responsibility of the Platform
            </h2>
            <ul className="list-disc list-inside space-y-3 text-muted-foreground">
              <li>We reproduce your details once you register on our platform on an "as is" and "as available" basis.</li>
              <li>Our obligation is only to provide an interface to its registered members to search for their prospect themselves without any assistance.</li>
              <li>The profile search conducted by any member and the matches shown thereof are automatically generated based on the partner preference set by you.</li>
              <li>We do not prohibit any member from sending interest to your profile or communicating with you based on their partner preference. You are at liberty to deny their interest or proceed further.</li>
              <li>We cannot guarantee or assume responsibility for any specific results from the use of the data available from our service.</li>
              <li>We shall safeguard sensitive user information using security standards, authentication mechanisms, access controls and encryption techniques.</li>
              <li>We cannot guarantee the complete protection of user data while it is in transit, or prevent any tampering of the data by a third party with malicious intent.</li>
              <li>We do not authenticate/endorse any information of any profile and hence you as a user need to verify the credentials and information provided by other users.</li>
            </ul>
          </section>

          {/* 5. Role and Responsibility of Member */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Users className="w-6 h-6 text-primary" />
              5. Role and Responsibility of Member
            </h2>
            <ul className="list-disc list-inside space-y-3 text-muted-foreground">
              <li>You shall safeguard your profile information by creating a strong password.</li>
              <li>You are requested to verify the credentials of any prospect, including marital status, educational qualifications, financial status, occupation, character, health status, etc., and satisfy yourself before making a choice. We shall not be liable for any misrepresentations made by any of its members.</li>
              <li>To get better search results, you are expected to provide a latest photograph which should not be more than 3 (three) months old. Providing old photographs, photographs of others, or inaccurate information shall be treated as a violation of these terms.</li>
              <li>Members are advised to refrain from entering into any financial transactions with prospects, using abusive language, being discriminatory, or sharing confidential data.</li>
              <li>Members are expected to visit our "Safe Matrimony" section for understanding safety measures.</li>
              <li>You agree that while using the platform, you will be guided by the terms and conditions of the platform.</li>
              <li>In case of finalization of marriage, you shall delete your profile or intimate us for removal.</li>
              <li>You agree to use secure devices, software and networks for accessing the services.</li>
              <li>You shall not use any kind of bots or automated processes to use, communicate or respond on the platform.</li>
              <li>You shall not probe, scan or test the vulnerabilities of the platform or any connected networks.</li>
              <li>You shall not make any payment to any of our employees. All payments shall be made only to the official account of the Organisation.</li>
              <li>You are expected to approach us to resolve complaints and shall not air grievances on social media.</li>
            </ul>
          </section>

          {/* 6. Customer Care */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Phone className="w-6 h-6 text-primary" />
              6. Customer Care / Customer Service
            </h2>
            <p className="text-muted-foreground mb-4">
              In the event you come across any concerns in our service, then please be free to contact us:
            </p>
            <div className="bg-card p-6 rounded-xl border border-border space-y-2">
              <p className="font-semibold">Brahmin Organisation Of India</p>
              <p className="text-muted-foreground flex items-center gap-2"><Mail className="w-4 h-4" /> Email: help@brahminorg.in</p>
              <p className="text-muted-foreground flex items-center gap-2"><Phone className="w-4 h-4" /> Phone: +91 98765 43210</p>
              <p className="text-muted-foreground flex items-center gap-2"><Landmark className="w-4 h-4" /> Address: 123, Heritage Lane, New Delhi, India</p>
            </div>
          </section>

          {/* 7. Medium of Communication */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <MessageSquare className="w-6 h-6 text-primary" />
              7. Medium of Communication
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              You hereby consent to receiving communication including promotional communications through any medium such as electronic mails, calls, SMS or through Whatsapp messages from the Organisation or its alliance partners. You are also entitled to set up your communications frequency from us.
            </p>
          </section>

          {/* 8. Confidentiality */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <ShieldCheck className="w-6 h-6 text-primary" />
              8. Confidentiality
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              Any feedback you provide to us shall be deemed to be non-confidential. We shall be free to use such feedback/information on an unrestricted basis. Further, by submitting the feedback, you represent and warrant that your feedback does not contain confidential or proprietary information of yourself or third parties and you are not entitled to any compensation or reimbursement of any kind from us for the feedback under any circumstances.
            </p>
          </section>

          {/* 9. Privacy of Membership */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Lock className="w-6 h-6 text-primary" />
              9. Privacy of Membership
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              To protect your privacy and understand our practices, please read and follow our Privacy Policy which also governs your visit to our platform. The personal information / data provided to us by you will be treated as confidential and in accordance with the Privacy policy and applicable laws and regulations.
            </p>
          </section>

          {/* 10. Grievance Officer */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Gavel className="w-6 h-6 text-primary" />
              10. Grievance Officer
            </h2>
            <p className="text-muted-foreground mb-4">
              In the event you come across any violation by another user, you may provide your concerns in writing or email us with a digital signature to:
            </p>
            <div className="bg-card p-6 rounded-xl border border-border space-y-2">
              <p className="font-semibold">Grievance Officer: Mr. Volunteer Name</p>
              <p className="text-muted-foreground flex items-center gap-2"><Mail className="w-4 h-4" /> Email: grievance@brahminorg.in</p>
              <p className="text-muted-foreground flex items-center gap-2"><Landmark className="w-4 h-4" /> Address: 123, Heritage Lane, New Delhi, India</p>
            </div>
            <p className="text-muted-foreground mt-4">
              The Grievance Officer shall handle complaints in relation to violations of computer resource usage as defined in the IT Rules, 2021.
            </p>
          </section>

          {/* 11. Disputes between Members */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Users className="w-6 h-6 text-primary" />
              11. Disputes between Members
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              Members are solely responsible for their communications with prospects. We expressly disclaim any responsibility or liability for any transactions, exchanges, or interactions between any members. We have no obligation to monitor any such disputes.
            </p>
          </section>

          {/* 12. Content Right */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <BookOpen className="w-6 h-6 text-primary" />
              12. Content Right
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              You acknowledge that you are responsible for the content and information you provide. By submitting content, you grant us a worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, and display your content in connection with our services. If your content is not in compliance with these terms, we may delete it and/or terminate your registration.
            </p>
          </section>

          {/* 13. Third Party Website */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Globe className="w-6 h-6 text-primary" />
              13. Third Party Websites
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              We may allow third parties to put up advertisements on our platform. These third-party websites are not governed by our Terms and Conditions. You click on links to third-party websites at your sole risk and responsibility.
            </p>
          </section>

          {/* 14. Limitation of liability */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <AlertTriangle className="w-6 h-6 text-primary" />
              14. Limitation of Liability
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              The Organisation shall under no circumstances be liable or responsible for any direct, indirect, special, exemplary, incidental, or consequential damages resulting from the use of our Platform. The exchange of profiles should not be construed as a matrimonial offer, recommendation, or advice from us. Our liability will at all times be limited to the amount paid, if any, by you for any specific paid package.
            </p>
          </section>

          {/* 15. Disclaimer */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Handshake className="w-6 h-6 text-primary" />
              15. Disclaimer
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed mb-4">
              Your access to and use of the services is at your own risk. YOU UNDERSTAND AND AGREE THAT THE SERVICES ARE PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS. We do not give any implied or explicit guarantee or warranty of marriage or alliance by you choosing to register on our Platform.
            </p>
            <p className="text-muted-foreground text-justify leading-relaxed">
              Notwithstanding anything contrary contained anywhere, under no circumstances shall we be held responsible or liable for any act or omission, any untrue or incorrect information submitted, any decision taken by you, any unauthorized or illegal act by a third party, any cybercrime, or any incident of force-majeure.
            </p>
          </section>

          {/* 16. Indemnity */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Shield className="w-6 h-6 text-primary" />
              16. Indemnity
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              By using our services you agree to defend, indemnify, and hold harmless the Organisation, its subsidiaries, affiliates, Directors, officers, agents, and other partners and employees from any loss, damage, liability, claim, or demand, including reasonable attorney's fees, made by any person through improper use of the service provided by us.
            </p>
          </section>

          {/* 17. Termination */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Ban className="w-6 h-6 text-primary" />
              17. Termination
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              We reserve our right to terminate your membership or suspend/delete your profile at our sole discretion without any notice if you violate these Terms, provide incorrect information, commit fraudulent activities, or act in an indecent/improper manner. Upon termination, your right to use or access the services will cease immediately.
            </p>
          </section>

          {/* 18. Jurisdiction and Applicable Law */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Scale className="w-6 h-6 text-primary" />
              18. Jurisdiction and Applicable Law
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              The registration of membership and all services are deemed to have been entered into within the territorial Jurisdiction of Chennai, India. You unconditionally agree that all disputes shall be governed by the Laws of India and submit to the exclusive jurisdiction of the appropriate court of law in Chennai, Tamil Nadu, India.
            </p>
          </section>

          {/* 19. Mode of Payment */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <CreditCard className="w-6 h-6 text-primary" />
              19. Mode of Payment
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              Payment would be in accordance with the prevailing RBI guidelines. Activation of paid service shall be subject to realization of the said payment. We use third-party payment gateways for collection of payment. By purchasing our paid package, you provide your explicit consent to share your mobile number with our authorized Payment Gateway partners.
            </p>
          </section>

          {/* 20. Refund and Assignment */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <BadgePercent className="w-6 h-6 text-primary" />
              20. Refund and Assignment
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              The payments made by any member by way of membership / renewal fee / auto renewal are treated as non-refundable. A member shall not assign or transfer their membership to any other person or entity.
            </p>
          </section>

          {/* 21. Renewal */}
          <section>
            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
              <Repeat className="w-6 h-6 text-primary" />
              21. Renewal
            </h2>
            <p className="text-muted-foreground text-justify leading-relaxed">
              We may automatically renew paid Memberships before the expiry of the term. You agree that your account will be subject to this automatic renewal feature. If you do not want your paid membership to automatically renew, you must cancel it.
            </p>
          </section>

          <div className="text-sm text-muted-foreground pt-8 border-t border-border">
            Last Updated: {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
          </div>

        </div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsAndConditions;